# @package _global_

defaults:
  - /sampler/base
  - /snr_schedule: inverse_sigmoid
  - /scale_schedule: constant
  - override /diffusion_process: sde/scale_snr

atol: 1e-4
rtol: 1e-4

sampler:
  _target_: tvsnr_mol.sampling.SNRRK
  method: "RK45"
  T: ${T}
  out_var_scaler: ${data_var}
  scale_input: True
  snr_key: "gamma"
  max_stoch_std: 1.
  min_stoch_std: 0.
  clip_stoch_std: False
  selected_stoch: False
  end_deterministic: False